version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8086:8086"
    environment:
      - DATABASE_URL=mongodb+srv://argentbank:Openclassrooms11@xiaosong.yupunes.mongodb.net/?retryWrites=true&w=majority&appName=xiaosong

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8085:80"
